### ISSUE TITLE
HCTIP - Nasty feedback on load

### ISSUE THREAD

**Issue by andrew-aaron** [sebastien-bouffier/Bidoo#94] opened 2019-05-08 09:39 UTC
OS (if applicable): Windows
Version: 0.6.28
![feedback](https://user-images.githubusercontent.com/7993131/57365299-20406600-71c8-11e9-8c52-ff0d942d94ca.png)

Sometimes when loading a patch HCTIP will get into some nasty high pitched self-oscillation. Notice in the screenshot that signal is still outputting out of HCTIP, even without an input signal.  
This seems to happen when there's a continuous sound feeding it. Having a sound that isn't a drone seems to be a work around.
Cheers.

**Comment by sebastien-bouffier** [comment] 2019-05-21 20:49
Hi Andrew,
Could you send me your patch please ?
I tried to reproduce sending a constant voltage and I did not managed to obtain the noise you describe.
I pushed a fix that sets output to zero if input is disconnected but it does not fix the pitch algorithm if needed
Best,

**Comment by andrew-aaron** [comment] 2019-05-23 00:50
https://www.dropbox.com/s/vdg1fo5g0ihp8l3/Rampage_Zen_Alpha_2%20%28bug%29.vcv?dl=0
Sometimes it does it, sometimes it doesn't. When I was trying to recreate the bug I chanced on it in another patch when pitching down with the knob. Too difficult to recreate though. 
In the linked patch, noise might appear on load. Start with your volume low!
Thanks for your consideration.

**Comment by sebastien-bouffier** [comment] 2019-05-24 11:22
Ok I can reproduce. I will take a look @ it.

**Comment by andrew-aaron** [comment] 2019-07-08 09:04
Thanks for looking into it and fixing!

**Comment by sebastien-bouffier** [comment] 2019-07-11 08:54
Hi, just pushed a new commit, I think the load issue is fixed (missing memset on arrays). But to be honest I think that there is still an issue when pitch factor goes below 1, I still work on that issue.

**Comment by sebastien-bouffier** [comment] 2019-07-27 00:38
Hi, I pushed 1.0.4 with a fix on the pitch shifter. I seems to be stable. I made a test with a pure sin wave because I noticed when searching that it was leading to what you described in your first post. Best.

**Comment by andrew-aaron** [comment] 2019-07-27 00:55
Thanks again!

**Closed** 2019-10-06 12:26 UTC
