### ISSUE TITLE
Non-appearance of two modules

### ISSUE THREAD

**Issue by ZuluEchoRomeOscar** [sebastien-bouffier/Bidoo#68] opened 2018-03-28 20:22 UTC
OS (if applicable): Linux {Debian 9}
Version (or "dev" if compiling from source): 0.6

Neither ChUTE nor OUAIve show up on the rack - they're in the menu but nothing happens when they're selected.

**Comment by sebastien-bouffier** [comment] 2018-03-28 23:01
Failed to load CHUTE, OUAIVE and LongSliderHandle svg on Linux ... not on W10 .... strange I did not change anything on those svg
I will try to make a new push an test. Stay tuned.

**Comment by AScustomWorks** [comment] 2018-03-28 23:40
If the error is happening on Linux, check if the name matches (lower and uppercase) on the svg file names vs the load svg call, Linux is too picky and  I had that happen to me a couple of times before ;)

**Comment by ZuluEchoRomeOscar** [comment] 2018-03-29 00:02
'picky' = 'secure'!

**Comment by sebastien-bouffier** [comment] 2018-03-29 07:13
>  'picky' = 'secure'!

I agree
I discovered that even if file names were changed git ignored those changes so I had to make a
`git config core.ignorecase false`
Push done and tested on my VM. So it should be ok on your Debian 9 config.

**Comment by ZuluEchoRomeOscar** [comment] 2018-03-29 08:50
Build fails with 
```
g++: error: ../../dep/lib/libcurl.a: No such file or directory
../../compile.mk:52: recipe for target 'plugin.so' failed
make: *** [plugin.so] Error 1
```

**Comment by sebastien-bouffier** [comment] 2018-03-29 16:27
strange, it was building/linking but 2 modules were not loaded because of svg and now there is a linking issue with libcurl which is shared across Rack ... do you confirm that this file is missing on your env in Rack/dep/lib ?

**Comment by ZuluEchoRomeOscar** [comment] 2018-03-29 16:33
I'm running from Andrew's SDK which does not appear to have /dep/lib at all!
And libcurl.a does not appear antwhere...

So this is an SDK problem, yes?

**Comment by ZuluEchoRomeOscar** [comment] 2018-03-29 16:52
https://github.com/VCVRack/community/issues/395#issuecomment-377296815

**Comment by ZuluEchoRomeOscar** [comment] 2018-03-29 17:05
I have now installed the full dev build to make your plugin in: it now fails at:
```
^CMakefile:3212: recipe for target 'src/libmpg123/id3.lo' failed
make[2]: *** [src/libmpg123/id3.lo] Error 1
Makefile:41: recipe for target 'lib/libmpg123.so' failed
make[1]: *** [lib/libmpg123.so] Interrupt
Makefile:27: recipe for target 'dep' failed
make: *** [dep] Interrupt
```

**Comment by sebastien-bouffier** [comment] 2018-03-29 21:04
I can't reproduce on my VM ... still searching .. at the same time I will have to redesign my makefile/makedeps .. lot of work to come ...

**Comment by cmountvpr** [comment] 2018-03-31 11:29
I will make a nice donation when the 0.6 Mac becomes available. :)

**Comment by sebastien-bouffier** [comment] 2018-03-31 11:41
hello thanks for your nice proposal :) it will be welcome but I take this opportunity to communicate that I did not expect that my modules where not 0.6 compliant ... last minute bad surprise. I hope to fix it this week-end.

**Comment by ZuluEchoRomeOscar** [comment] 2018-04-01 10:17
Happy to report that the latest code builds successfully on my Linux box, and that all modules appear to be present and correct. Just missing a target for `MAKE DIST` now...

**Comment by ZuluEchoRomeOscar** [comment] 2018-04-01 14:48
I should note that I have changed system since the last attempt - I was on Debian, and am now on Arch.

Just a minor thing that's taken over my weekend!

**Comment by sebastien-bouffier** [comment] 2018-04-01 17:01
:) what do you mean by 

> Just missing a target for MAKE DIST now...

I have just tested a make dist on my linux vm and everything seems to be fine

**Comment by sebastien-bouffier** [comment] 2018-04-03 12:16
Dear musician/dev users I have rolled back to my previous way of linking curl for antN. After several tries I achieved to get closer to a static linking for curl but I didn't push because it was still not working. 
Btw there was something still unclear to me regarding this issue ... it was working on 0.5 in spite of not static linking. So I made the following test => rollback to my previous approach i.e. dyn link for curl and deployed my plugin on a W10 machine without any dev env installed. Under Rack 0.6 my 0.6.1 plugin works fine. I can build/link/run and play on my linux VM ... so the last thing to check is on mac os x .. If someone can build dist test on mac it would be great. 
I apologize for the delay but those lasts days have been quite complicated and I admit I could have made thing a little bit more fluid in terms of communication on FB but as you may know I am really reluctant to use that media for many good and bad reasons.

**Comment by sebastien-bouffier** [comment] 2018-04-16 23:27
I close this thread to clean my issue list. Do not hesitate to contact me if you think that it is not relevant.

**Closed by sebastien-bouffier** 2018-04-16 23:27 UTC
