### ISSUE TITLE
Speed becomes not normalled to 0.5 decimal when midi mapped

### ISSUE THREAD

**Issue by vcvrackideas** [sebastien-bouffier/Bidoo#151] opened 2020-04-21 11:33 UTC
OS (if applicable): win
Version (or "dev" if compiling from source): 1.1.8
With midi mapped Speed knob I got other decimal values than turning with mouse like that - 
![2020-04-21_14-30-15](https://user-images.githubusercontent.com/42435368/79861375-fe41f280-83dc-11ea-93f2-56bd63c7ed62.png)
Or it's just how display works and doesn't make sense as bug?

**Comment by sebastien-bouffier** [comment] 2020-04-23 08:51
Hi I want to be able to multiply the clock by 0.5, 1, 2 up to 16 times.
So the speed param goes from 1 to 32 with a snap knob that jumps between integers and I store 0.5 times the value of the knob. I will dig into midi mapping in order to fix that issue.
Cheers

**Comment by sebastien-bouffier** [comment] 2020-04-24 22:53
Issue found. It is the same as for PROB. I have limited speed to x1 x2 x3 x4 in the next version, I hope you will still be able to make music with the module :)
Cheers

**Comment by sebastien-bouffier** [comment] 2020-05-04 12:55
Hi @vcvrackideas  I close this thread since it is fixed in 1.1.21 do not hesitate to reopen it if you think the issue is still there.

**Closed as completed by sebastien-bouffier** 2020-05-04 12:55 UTC
Labels: bug
