### ISSUE TITLE
VCV Crash

### ISSUE THREAD

**Issue by EdwardRosenfeld** [sebastien-bouffier/Bidoo#116] opened 2019-07-27 21:58 UTC
OS (if applicable): Latest version of Biddoo plugins causes a crash in my windows platform version of VCV Rack.

**Comment by Coirt** [comment] 2019-07-27 22:28
duplicate of #115

**Comment by EdwardRosenfeld** [comment] 2019-07-28 04:59
Thanks for the quick fix...

**Comment by sebastien-bouffier** [comment] 2019-07-29 08:57
Hi @EdwardRosenfeld  I am working on that issue but to be honest I do not know where it does come from .... stay tuned. I made a release with a W dist so you can try to replace your bidoo folder with the one contained in the last release.

**Closed as completed** 2019-08-11 07:39 UTC
