### ISSUE TITLE
Bidoo-0.5.22-mac.zip

### ISSUE THREAD

**Issue by AScustomWorks** [sebastien-bouffier/Bidoo#53] opened 2018-02-22 17:20 UTC
Here you go Seb ;)
[Bidoo-0.5.22-mac.zip](https://github.com/sebastien-bouffier/Bidoo/files/1748831/Bidoo-0.5.22-mac.zip)

**Comment by a1laserboy** [comment] 2018-02-22 17:55
This doesn't work on OSX, is it built against 0.5.1 or 0.6?

**Comment by AScustomWorks** [comment] 2018-02-22 18:10
What doesn't work? the tag says the build version, and nothing was changed from the source code (just cloned  and compiled for mac):
![bidoo](https://user-images.githubusercontent.com/34798768/36555986-41ed65a0-17c9-11e8-8e59-f2d4fba4a7e7.jpg)

**Comment by a1laserboy** [comment] 2018-02-22 18:53
Bidoo doesn't show up at all in rack using this version. I uncompressed it, overwrote the old xx.21 as I would normally. I'll try again.

**Comment by AScustomWorks** [comment] 2018-02-22 19:08
![bidoo](https://user-images.githubusercontent.com/34798768/36558715-8239579c-17d1-11e8-89d0-42e1e089cd3a.jpg)

**Comment by a1laserboy** [comment] 2018-02-22 19:14
Odd, I even downloaded it again but no luck. Sorry for the hassle. Maybe i'm being dumb.

**Comment by nay-seven** [comment] 2018-02-22 19:19
hello,
no, i confirm same issue with 5.22 release on Yosemite here, no plugins visible

**Comment by a1laserboy** [comment] 2018-02-22 19:31
Phew, I thought I was going crazy for a while

**Comment by AScustomWorks** [comment] 2018-02-22 19:36
Maybe the zip file got corrupted when uploaded, try again with this one:
[Bidoo-0.5.22-mac.zip](https://github.com/sebastien-bouffier/Bidoo/files/1749278/Bidoo-0.5.22-mac.zip)

**Comment by phdsg** [comment] 2018-02-22 19:40
@AScustomWorks you were a bit faster :) had to paste the sum

better take freddy's (he uses a real mac).
but just in case, here's the one i just made...

_[Bidoo-0.5.22-mac.zip](https://github.com/sebastien-bouffier/Bidoo/files/1749279/Bidoo-0.5.22-mac.zip)
`f5b9ab80ddf39837ff43cfe9c1cb93552e88bc00114c8eda24f4c59472c0015c  Bidoo-0.5.22-mac.zip
`_

**Comment by a1laserboy** [comment] 2018-02-22 19:44
Thanks guys for sticking with it :) but for me neither work still though. 

This is a weird one.

**Comment by phdsg** [comment] 2018-02-22 19:48
maybe just extracted into the wrong folder?

**Comment by AScustomWorks** [comment] 2018-02-22 19:54
Just tried both versions downloading from here, def something is going wrong. Here's my working folder on wetransfer:
https://we.tl/n2m8rgOB2r

**Comment by a1laserboy** [comment] 2018-02-22 19:54
for me, I extract into the download folder (by clicking the download in Chrome), then drag it to plugins from the downloads folder where I'm taken to by previous click, confirming I want to overwrite the older one. Same way as always with every plugin since November. I've done it enough to be fairly sure I'm doing it right.

Does downloading, extracting and move work for you guys? (rather than relying on your local made version)

**Comment by a1laserboy** [comment] 2018-02-22 19:56
Thanks for the new test Freddy, I still get the same from your Wetransfer too.

**Comment by AScustomWorks** [comment] 2018-02-22 20:02
Another test, compiled again, tested on 0.5.1, compressed the zip via finder:
```
55397d0b200cfaf1c15d1554ff151f5cf705a1aa9d064e34e8f9b07b69e66743
```
[Bidoo-0.5.22-mac.zip](https://github.com/sebastien-bouffier/Bidoo/files/1749365/Bidoo-0.5.22-mac.zip)

**Comment by a1laserboy** [comment] 2018-02-22 20:10
Same. Don't know how to do the checksum thing.

**Comment by AScustomWorks** [comment] 2018-02-22 20:29
Just tried downloading the last one, to be completely sure first deleted the working folder, ran rack and got no Bidoo module popup window, then copied the unzipped folder to plugins, ran rack again, everything fine. Not sure what else to try to make it work for you.

**Comment by nay-seven** [comment] 2018-02-22 20:54
same as a1laserboy , test all your versions without success
and i'm also used to update plugins since a while

gone to test on another machine with El capitan ( btw a1laserboy, wich OS version do you use ?)

**Comment by a1laserboy** [comment] 2018-02-22 21:08
10.12.6

**Comment by nay-seven** [comment] 2018-02-22 21:24
ok, so tested on El capitan and High Sierra, no more success

**Comment by sebastien-bouffier** [comment] 2018-02-23 07:01
thanks again :)

**Comment by sebastien-bouffier** [comment] 2018-02-23 09:39
Hello hello I just would like to make sure that all of you in this thread is able to use 0.5.22 on OS X now.
I posted on FB a message to inform users that the update is available and Peter wrote 

> hm... another update of modules that now don't load in my vcvrack 0.5.1 - presumably because i am still on osx 10.8.5. any idea for a solution besides updating the os?

**Comment by nay-seven** [comment] 2018-02-23 09:56
Hello,
no as said in my previous answer , no way here on several different OS version, and I've ask on the VCV French group and 3 guys answer the same, they don't see the modules. Clement try to recompile and try different things (suppress module antn, change make dist) , but no way.

**Comment by sebastien-bouffier** [comment] 2018-02-23 10:15
haaaaaaaa ... ok ok ... according to my understanding it works on AS mac OSX version but not the others ... I wish I had a mac or a OSX running under a VM to check what's wrong. I had to setup a Linux VM for this version and I think I will have to find a way to work under OS X too.  Thanks a lot for the efforts of other dev/users to help.

**Comment by AScustomWorks** [comment] 2018-02-23 16:30
Just for the record, the plugin I compiled runs fine on both v 0.5.n dev and public rack releases, and I'm on OS X 10.12.6.
This issue is really weird :(

**Comment by phdsg** [comment] 2018-02-23 16:36
indeed.
it'd be interesting to see rack's console output or log.txt from @nay-seven / @a1laserboy.

**Comment by a1laserboy** [comment] 2018-02-23 16:44
From Freddy's wetransfer:

'''[warning] Failed to load library /Users/martinkapp/Documents/Rack/plugins/Bidoo/plugin.dylib: dlopen(/Users/martinkapp/Documents/Rack/plugins/Bidoo/plugin.dylib, 2): Library not loaded: /Users/Freddy/Rack-0.5.0/Rack/dep/lib/libcurl.4.dylib
  Referenced from: /Users/martinkapp/Documents/Rack/plugins/Bidoo/plugin.dylib
  Reason: Incompatible library version: plugin.dylib requires version 10.0.0 or later, but libcurl.4.dylib provides version 7.0.0
'''

**Comment by a1laserboy** [comment] 2018-02-23 16:46
I'm assuming it's looking for libcurl in a place that doesn't exist on my machine.

**Comment by phdsg** [comment] 2018-02-23 16:47
oh no. curl weirdness **again**. thx 4 the log.

**Comment by a1laserboy** [comment] 2018-02-23 16:48
I should have thought about doing that last night

**Comment by AScustomWorks** [comment] 2018-02-23 16:48
could that be related to developers having already installed v0.6dev too?

**Comment by phdsg** [comment] 2018-02-23 17:03
this is probably related to all the other issues that came up with the new module antn which uses curl and another library. seems the linking is all different for the three platforms and he has to fix it for osx like he fixed it for linux. might take a few shots.
until then, compiling it yourself is probably the only way to get latest.

**Comment by a1laserboy** [comment] 2018-02-23 17:08
I'm free to test any time if needed. Perhaps I need to set up a way to get email alerts on this thread so I don't make you all wait so long again. Thanks for sticking with it:) For now I'll go back to the old one.

**Comment by sebastien-bouffier** [comment] 2018-02-23 17:11
thanks for your efforts I will take a look at this liking issue and i hope i will be able to solve it asap. stay tuned

**Comment by phdsg** [comment] 2018-02-23 17:29
here's a stripped version.
[Bidoo-0.5.22-noANTN-mac.zip](https://github.com/sebastien-bouffier/Bidoo/files/1752545/Bidoo-0.5.22-noANTN-mac.zip)

`3fffab33059c6766eee246435f239a564a5337ab9778b67264dbb745364b68aa  Bidoo-0.5.22-noANTN-mac.zip
`

**Comment by a1laserboy** [comment] 2018-02-23 17:33
Thanks, confirmed working here :)

**Comment by nay-seven** [comment] 2018-02-23 18:03
yes, works here too ! Thanks

**Comment by sebastien-bouffier** [comment] 2018-02-23 21:52
So ... I made some research over the net and maybe the issue comes from `DYLD_LIBRARY_PATH` value that may point to a folder containing a Curl library but different from the one included in Rack's dependencies. So I would suggest a test ... replacing 
```
ifeq ($(ARCH), mac)
	LDFLAGS += -L../../dep/lib -lcurl src/dep/lib/libmpg123.a
endif
```
by 
```
ifeq ($(ARCH), mac)
	LDFLAGS += -L../../dep/lib/libcurl.a src/dep/lib/libmpg123.a 
endif
```
in my makefile and rebuild and retest. At the same time I still don't understand why Rack's requests for plugins' download works and not antN ...

**Comment by phdsg** [comment] 2018-02-23 22:04
applied, built, loads fine. here's one for the real mac owners.
`48e7c4095c05c9e04ceb2d810bb46478aa60453f041874a3f80c7ed4ffbdb073  Bidoo-0.5.22-ANTN_fix1-mac.zip
`
[Bidoo-0.5.22-ANTN_fix1-mac.zip](https://github.com/sebastien-bouffier/Bidoo/files/1753302/Bidoo-0.5.22-ANTN_fix1-mac.zip)

**Comment by sebastien-bouffier** [comment] 2018-02-23 22:44
thanks a lot

**Comment by nay-seven** [comment] 2018-02-23 23:06
looks ok, but Dtroy looks buggy

**Comment by phdsg** [comment] 2018-02-23 23:08
got a screenshot?

**Comment by nay-seven** [comment] 2018-02-23 23:19
oh, sorry, looks not on a graphic way ( 
steps don't work at first , after a rack restart , better, but it's late so maybe me, will try to test better tomorrow

**Comment by sebastien-bouffier** [comment] 2018-02-24 08:28
Yes seen, I made my tests with existing projects so I did not see that a new instance of dTrOY stays on the first step. This is a regression due to gate time & slide params fix. I will try to fix it asap.

**Comment by phdsg** [comment] 2018-02-24 19:17
0.5.23 build and loads ok. don't know how it runs.
on minor thing the compiler (linker) throws at the end...
`ld: warning: -L path '../../dep/lib/libcurl.a' is not a directory
`

**Comment by a1laserboy** [comment] 2018-02-24 19:22
Just got to my computer - antN works on the last 0.5.22 build :)

Sorry for delay, been a bit under the weather.

**Comment by phdsg** [comment] 2018-02-24 19:25
nice. thx @a1laserboy and
well done @sebastien-bouffier

**Comment by phdsg** [comment] 2018-02-26 22:45
here's 0.5.23 if you wanna use it:

[Bidoo-0.5.23-mac.zip](https://github.com/sebastien-bouffier/Bidoo/files/1760529/Bidoo-0.5.23-mac.zip)

`bd6963b6876ffd133d27c504c5b0043e9ac501951baacfb90de9e34d7669576f  Bidoo-0.5.23-mac.zip`

`[info] Loaded plugin ./plugins/Bidoo/plugin.dylib`

**Comment by sebastien-bouffier** [comment] 2018-02-26 23:04
Yes thanks.

**Comment by a1laserboy** [comment] 2018-02-26 23:07
Thank you :)

Is there anything we need to test specifically?

**Comment by sebastien-bouffier** [comment] 2018-02-26 23:47
No 0.23 is better than 0.22 but it still has some issues on antN .. I made the big mistake of not doing a branch before 0.6 upgrade and now it is a pain to go back. So I upload 0.23 in case someone cannot build and use 0.6 but I would recommend using the last version of the source i.e 0.6.dev

**Comment by phdsg** [comment] 2018-02-26 23:54
you can still make a branch of a older state...
go to your github repo, click on the branch button, select i.e. 0.5.23 (tag), when it has reloaded the page, click the button again and type a new branch name into the field and it will create a branch from that moment.

**Comment by sebastien-bouffier** [comment] 2018-02-27 08:13
done thanks

**Comment by sebastien-bouffier** [comment] 2018-03-04 17:49
Hello does anyone could build a mac dist for my last push on 0.5 branch please ?
Best,

**Comment by phdsg** [comment] 2018-03-05 08:49
`957b67e9c5e0bc8dd8aa7c6ab0666a1788252c049d33ee133b72ff45d1ecbf64  Bidoo-0.5.24-mac.zip`
[Bidoo-0.5.24-mac.zip](https://github.com/sebastien-bouffier/Bidoo/files/1780098/Bidoo-0.5.24-mac.zip)

**Comment by sebastien-bouffier** [comment] 2018-03-05 09:03
Thanks a lot

**Comment by sebastien-bouffier** [comment] 2018-04-16 23:26
I close this thread to clean my issue list. Do not hesitate to contact me if you think that it is not relevant.

**Closed by sebastien-bouffier** 2018-04-16 23:26 UTC
