### ISSUE TITLE
VCV Rack 1.1.3 crashes when opening module library and searching

### ISSUE THREAD

**Issue by jctarvin** [sebastien-bouffier/Bidoo#118] opened 2019-07-28 17:01 UTC
OS (if applicable):
Version (or "dev" if compiling from source):

**Comment by Coirt** [comment] 2019-07-28 17:03
duplicate of #116 and #115 

Also there should be an update to bidoo `1.0.4 → 1.0.3`

**Comment by jctarvin** [comment] 2019-07-28 17:05
Working on a project and needed to look for "mixers". Module browser crashed VCV Rack 1.1.3. Restarted.....module browser did same thing. Can't do a search in it.

Screenshot of notice and log file are attached.

[log.txt](https://github.com/sebastien-bouffier/Bidoo/files/3439387/log.txt)
![Screenshot (31)](https://user-images.githubusercontent.com/46425160/62010405-3acb1100-b11f-11e9-91b2-677714c74cb1.png)

**Comment by Coirt** [comment] 2019-07-28 17:23
I have no idea what is crashing but I do not think it is bidoo:
```
[961.967 fatal src/main.cpp:38] Fatal signal 22. Stack trace:
21: ZN4rack10appDestroyEv 0x456415
20: raise 0x52c4a7e0
19: abort 0x52c4edd0
18: assert 0x52c4b080
17: ZN4rack3app12ModuleWidget8addInputEPNS0_10PortWidgetE 0x495540
16: ZN9SUMWidgetC1EP3SUM 0xad94870
15: ZZN4rack11createModelI3SUM9SUMWidgetJEEEPNS_6plugin5ModelERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEN6TModel22createModuleWidgetNullEv 0xad98b20
14: ZN4rack3app8ModelBox4drawERKNS_6widget6Widget8DrawArgsE 0x77a010
13: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x4a691c
12: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x4a691c
11: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x4a691c
10: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x4a691c
9: ZN4rack2ui12ScrollWidget4drawERKNS_6widget6Widget8DrawArgsE 0x4a3184
8: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x4a691c
7: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x4a691c
6: ZN4rack6widget6Widget4drawERKNS1_8DrawArgsE 0x4a691c
5: ZN4rack6Window3runEv 0x4594ca
4: main 0x7a0000
3: main 0x7a0000
2: main 0x7a0000
1: BaseThreadInitThunk 0x54db4020
0: RtlUserThreadStart 0x55803670
```

Do you have any KlirrFactory plugins installed?

**Comment by jctarvin** [comment] 2019-07-28 22:34
Hi, Phil.... thanks for the reply.

To answer you question, yes, I have the Hall of Fame modules installed. Haven't used hardly any yet.

After I made that post, it started behaving normally. Go figure. It feels like if I save the patch it might behave normally afterward. And, believe me, I'm saving often.

⁣John​


-------- Original Message --------

**Comment by Coirt** [comment] 2019-07-28 22:36
Update KlirrFactory!

**Comment by sebastien-bouffier** [comment] 2019-07-29 08:54
Hi @jctarvin  I admit I do not know why my module crashes Rack. I made a release with a local dist on my computer so if you are under W7 ou W10 you can try to replace your bidoo folder with this dist it might work.
Best.

**Comment by jctarvin** [comment] 2019-07-29 15:13
Sebastian,

Sorry if I posted in the wrong place on github. I have no idea if it's any particular module(s) causing the issue. Certainly wasn't saying it was a bidoo module. After posting yesterday, rack 1.1.3 has behaved very well. Only one other crash in the module browser. 

When it was happening regularly, it was a pain in the butt. Sure it will all get resolved. In the meantime, I'll just keep having fun! 

Thanks for your concern!

⁣John​


-------- Original Message --------

**Comment by sebastien-bouffier** [comment] 2019-08-12 18:24
Hi John I hope you do not face any crash anymore. Let me know if everything works fine.
Cheers

**Comment by sebastien-bouffier** [comment] 2019-08-19 18:43
Seems to be fixed

**Closed as completed by sebastien-bouffier** 2019-08-19 18:43 UTC
