### ISSUE TITLE
zOu MAi Operational Problems

### ISSUE THREAD

**Issue by midiguru23** [sebastien-bouffier/Bidoo#164] opened 2020-10-09 20:49 UTC
1.1.26 (Windows build). I like this sequencer's features! But it's almost impossible to use. When I stop Clocked, zOu MAi goes on playing for another step or two -- it fails to stop. This is okay while I'm developing a patch, but it makes the patch unplayable in an actual performance situation.

Sometimes when it stops a gate is left open. This is clearly wrong. All gates must be shut off, because some synth envelopes may have a non-zero sustain level.

When it's started again after stopping and resetting, some of the tracks do not play their first note.

**Comment by sebastien-bouffier** [comment] 2020-10-11 11:44
Hi, @midiguru23  I take your points and I will try to solve them.
Gates opened when the sequencer is stopped will be easily fixed.
The stop failing issue will be more difficult to fix and I would like to share with you the reason why and hopefully you may help me. I would like to keep the "trim" feature available. This feature requires (as I understand it should be implemented) that I compute an expected tempo based on clock input and keep on moving forward in the sequence even if the next clock tick does not occur, tempo change is complex to manage with that feature . That is the reason why the sequencer stops after 2 or 3 clock ticks are too spaced and not before. If I add a new input that starts and stops the sequencer is really easy for me but is it what you expect ?

**Comment by midiguru23** [comment] 2020-10-11 20:01
I think I see what you're saying. Currently zOu MAi doesn't have a Run input (as is found on Impromptu Phrase-Seq-16, for instance). So zOu MAi will stop playing only after several clock pulses are not received.

The Trim feature (which is excellent, by the way!) moves a note earlier or later. But I'm not sure that would be affected. If you add a Run/Stop input (a momentary trigger pulse input), then the sequencer would stop immediately if it's running and sees a pulse at that input.

If the clock pulses start again when there has been no Reset, the sequencer continues from wherever it stopped -- and THAT would be more difficult if it stops just before a note with a Trim, because the software wouldn't know how to calculate the Trim offset timing. You might try just ignoring the Trim value of a step in a case where (a) there is no Reset and (b) the external clock pulses are starting after having ceased for some period of time. Or you could keep the Trim calculation based on the previous tempo (until enough clock pulses have arrived that you can calculate a new time value for the Trim).

I hope this makes sense! I'm not a real programmer!

**Comment by sebastien-bouffier** [comment] 2020-10-13 14:50
Hi, RUN input added in 1.1.27. Let me know if it works as expected.

**Comment by midiguru23** [comment] 2020-10-21 03:11
This is a very big improvement! Many thanks. I'm encountering an intermittent problem in which it starts the first note one step too late. This quick video illustrates the problem. Sometimes the first note plays on the 2nd pulse, or something of the sort.

[start_late.zip](https://github.com/sebastien-bouffier/Bidoo/files/5413033/start_late.zip)

**Comment by sebastien-bouffier** [comment] 2020-10-22 12:36
Hi, it may be fixed in 1.1.28 to come (just pushed) :)
Best.

**Comment by midiguru23** [comment] 2020-10-23 00:12
I'm seeing the same thing in 1.1.28. It only happens about once every ten times when I hit Run (in Clocked). I tried changing the settings for Clocked to send a Reset, but that didn't help.

**Comment by sebastien-bouffier** [comment] 2020-10-23 14:18
Please could you perform a test with another clock such as my clock i.e. tOCAnTe ? You can use the M(easure) output to send a reset if you need. To make a 16 steps measure you can send clock with the /4 out and set beats to 16 so you have a 16/4 measure.
The Run out port is under the Run button.

**Comment by midiguru23** [comment] 2020-10-23 16:31
It seems to work much better with tOCAnTe. When I look at the Reset signal on the VCV Scope, I can see why. The Reset sent by tOCAnTE is much longer than the Reset from Clocked. (I don't think I have a way to measure the number of milliseconds.) Later today I'll try sending the Reset from Clocked through the Alikins Gate Length module to see if that fixes the problem.

**Comment by midiguru23** [comment] 2020-10-23 16:37
No, adding Gate Length (set to 1ms for the Clocked Reset signal) doesn't help. My next guess is, it may relate to the _order_ in which the Reset and the first clock pulse arrive. But that's just a guess.

**Comment by sebastien-bouffier** [comment] 2020-10-23 18:54
Thanks for your test, and that is one reason why it seemed fixed on my side because I test with tOCAnTe. Pulses generated by tOCAnTe are 1ms long according to VCV recommendations [https://vcvrack.com/manual/VoltageStandards](https://vcvrack.com/manual/VoltageStandards). In the last version I added the timer approach recommended in the same article to avoid unexpected behaviors with 1ms latency and with tOCAnTe it seems to be fine but with "clocked" even if I set the pulse width to 1ms I can reproduce your issue ... it is a nightmare. Just because I am curious, why do you prefer "clocked" to tOCAnTe ? What are the missing features that are really important ?
Best

**Comment by midiguru23** [comment] 2020-10-23 19:33
I always use Clocked. There are many more choices for the divisor/multiplier knobs, which is useful. Two Clocked modules can be chained, so you can very easily have six different divisor/multipliers running at the same time. I don't use the Swing or Pulse Width knobs often, but once in a while Pulse Width is useful. The x24 multiplier is very useful for clocking both Impromptu Gate-Seq and Valley Topograph.

**Closed as completed** 2022-07-06 16:37 UTC
