### ISSUE TITLE
zou mai quantiser issue

### ISSUE THREAD

**Issue by Gbary1974** [sebastien-bouffier/Bidoo#200] opened 2022-05-24 18:31 UTC
OS (if applicable):Mac OS Monterey
Version (or "dev" if compiling from source):
Great sequencer and lots of possibilities but Im having trouble with the quantisation. If I select C as the root I can add notes of the whole scale when programming a sequence.. but if I select for example A as the root note, when programming the sequence only notes from A and above can be selected in the sequence, so A to B, if I select any notes from C to A i just get an A. This seems to be the case whatever scale root I select so F will only register notes from F to B C to F all come out as F.

**Comment by sebastien-bouffier** [comment] 2022-05-25 18:26
hi @Gbary1974  got it, i will fix it asap because the root cause is in diktat my quantizer and the impact is across all my sequencers ...
stay tuned
best.

**Comment by sebastien-bouffier** [comment] 2022-07-06 16:21
Hi @Gbary1974 it should be fixed in 2.0.15 to come. Just pushed.
Best.

**Comment by Gbary1974** [comment] 2022-07-08 05:40
That’s great news, loving your work.

**Comment by sebastien-bouffier** [comment] 2022-07-08 21:50
thanks a lot :)

**Comment by sebastien-bouffier** [comment] 2022-07-18 09:22
Hi @Gbary1974 I close the issue. Let me know if you consider the bug is not fixed.
Best

**Closed as completed by sebastien-bouffier** 2022-07-18 09:22 UTC
